### ISSUE TITLE
Heads do not drop from non-angry wolves

### ISSUE THREAD

**Issue by Aloki** [MLDEG/AllMobHeads#14]
### Datapack version

10.2

### Description

1) Heads from angry wolves drop as usual (including the default pale variant). However, they do not drop from non-angry wolves at all.
2) Except for the default pale variant - a head with a red collar drops from it. According to the output of the /data get entity command, all wolves have the CollarColor:14b property. The wiki also says "Present even for wild wolves (but does not render)".

### Steps to reproduce

Try getting the head from a non-angry wolf (including the correct variant from the default pale variant when wild).

### Expected behavior

Should drop heads from non-angry wolves, including the correct variant from the default pale variant when wild.

**Comment by MLDEG** [comment]
Are you using a vanilla server?
Do you use another datapack?

Because in my testing world, I have zero problem :/

![2024-08-06_00 59 08](https://github.com/user-attachments/assets/93ee4460-7606-4e40-820c-d2ca1ce6455f)
![2024-08-06_00 59 26](https://github.com/user-attachments/assets/efe055b9-31a5-41a4-ba26-57544ab2c863)
![2024-08-06_00 59 59](https://github.com/user-attachments/assets/e49df4db-75a2-42e7-acf6-3929f277302f)

**Comment by Aloki** [comment]
I apologize. I ran additional tests, something is wrong with CraftBukkit. I will report the bug to its developers.

**Comment by MLDEG** [comment]
Thanks for the feedback
