### ISSUE TITLE
Ominous Bottles not dropping properly when 1.21 experimental features enabled

### ISSUE THREAD

**Issue by DamiansStupidCodeLMAO** [MLDEG/AllMobHeads#5]
### Datapack version

9.2

### Description

When a captain pillager is killed, it doesn't drop an ominous bottle.

### Steps to reproduce

1. Find outpost
2. Kill captain
3. no bottle :(

### Expected behavior

When you kill the captain, it should drop an ominous bottle (while still having a chance of dropping its head)

### Anything else to note?

I was able to fix this myself by manually reinserting the Ominous Bottle code into the datapack, though I do not trust this as a true solution (i'm not good at datapack making and i highly expect that not to work if you don't enable 1.21 features)

**Comment by MLDEG** [comment]
Could you show me the fix you made?
Because it's odd it should work normally because I took the vanilla loot tables from the last snapshot for the datapack.
Thanks !

**Comment by MLDEG** [comment]
So I tested creatively with the version you are using and I have the loot from the ominous bottle :/
So I don't know where your problem comes from...
![2024-05-16_03 21 56](https://github.com/MLDEG/AllMobHeads/assets/90324978/4527ea1e-c238-476f-94db-325ec44791bf)
![2024-05-16_03 21 59](https://github.com/MLDEG/AllMobHeads/assets/90324978/c23cb49a-dcab-4b72-ba7c-51ada8e1213e)
